### ISSUE TITLE
数据不够全

### ISSUE THREAD

**Issue by cloud-jie** [momosecurity/FindSomething#12]
在使用过程中，我发现与[JSFinder](https://github.com/Threezh1/JSFinder)内容有些出入，使用此插件没有获取到任何数据，但使用[JSFinder](https://github.com/Threezh1/JSFinder)却能获取到，还有我能够使用此插件完全代替[JSFinder](https://github.com/Threezh1/JSFinder)吗？

**Comment by ResidualLaugh** [comment]
可以提供下当时测试的哪个网站，使用[JSFinder](https://github.com/Threezh1/JSFinder)的命令及测试结果吗，我分析下差别。如果可以优化，我会继续更新代码，能否完全代替[JSFinder](https://github.com/Threezh1/JSFinder)则需要你自己评估。

**Comment by ResidualLaugh** [comment]
我比较了JSFinder和FindSomething的正则表达式（url提取规则），FindSomething确实缺少./和../格式的路径匹配，并缺少纯文件格式的路径匹配。本次更新#13 ，我增加了./和../格式的路径匹配， 考虑到插件的应用场景，不关注纯文件格式路径。
此外，我还增加匹配了url中有端口号的格式，如https://github.com:9999/path
