### ISSUE TITLE
可以自定义规则嘛

### ISSUE THREAD

**Issue by qaqllz** [momosecurity/FindSomething#17]
想添加一些自己常用的规则，比如account password username之类的

**Comment by ResidualLaugh** [comment]
希望添加哪些规则，可以整理在这个issues中，后面我来加上。

**Comment by ResidualLaugh** [comment]
本次更新添加了几条规则。是希望能配置自己的规则吗？这个下个版本再考虑加上吧，2.0.8刚加上配置页。
