### ISSUE TITLE
全路径

### ISSUE THREAD

**Issue by cloud-jie** [momosecurity/FindSomething#19]
我发现每次在使用时都需要多一个步骤，或是手动拼接再批量打开，或是复制进burp直接爆破，等等
如果可以，希望可以有一个功能是导出绝对路径
![image](https://user-images.githubusercontent.com/63632785/184597302-3af2d94b-9719-4f58-8d5c-e811631ae883.png)

测试网址：http://219.142.83.35/survey/
FindSomething
![image](https://user-images.githubusercontent.com/63632785/184599325-591b772d-4237-40d6-b4eb-a7fe26735131.png)
jsfinder
![image](https://user-images.githubusercontent.com/63632785/184599057-8c87a6a5-6e6b-4526-a384-c9a5dfa41959.png)

**Comment by ResidualLaugh** [comment]
好，下个版本支持上
