### ISSUE TITLE
提取敏感信息时，只能返回最后一条正则匹配到的数据

### ISSUE THREAD

**Issue by xiaoliangli1128** [momosecurity/FindSomething#22]
![图片](https://user-images.githubusercontent.com/66862331/200276247-c671f78b-c357-412d-a8e7-409fa0f2422b.png)

如图正则中的5条语句，网页匹配到只显示最后一一条
![图片](https://user-images.githubusercontent.com/66862331/200276526-c5a552ae-a02a-4a2b-935d-8ab9eb9fe1e5.png)

![图片](https://user-images.githubusercontent.com/66862331/200276686-40a80412-dfb9-48d2-90e9-98320fd2f664.png)
这个 ak 和secret没法显示

**Comment by ResidualLaugh** [comment]
好的，我会尽快排查一下问题。

**Comment by ResidualLaugh** [comment]
是的，我也刚找到。稍晚些会更新一个新版本来修复这个问题。

**Comment by ResidualLaugh** [comment]
#23 #24 修复了这个问题。感谢反馈～
