### ISSUE TITLE
希望增加一个超链接  每次复制拼接有点麻烦

### ISSUE THREAD

**Issue by lxy6515** [momosecurity/FindSomething#33]
因为只能全部导出或者一个一个复制，偶尔还有一些特别长导致挡住视线不好复制的情况
![image](https://user-images.githubusercontent.com/46446782/233376221-ad9465a6-e994-4356-bb38-bbb1688caa36.png)

**Comment by lxy6515** [comment]
是的&nbsp;


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月20日(周四) 晚上11:24
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;&quot;l x ***@***.***&gt;;
主题: Re: [momosecurity/FindSomething] 希望增加一个超链接  每次复制拼接有点麻烦 (Issue #33)




 
你是说path吗？
 
&mdash;

**Comment by ResidualLaugh** [comment]
我考虑一下

**Comment by lxy6515** [comment]
可以考虑一下点击跳转到到该链接&nbsp;或者复制完整链接


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月20日(周四) 晚上11:45
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;&quot;l x ***@***.***&gt;;
主题: Re: [momosecurity/FindSomething] 希望增加一个超链接  每次复制拼接有点麻烦 (Issue #33)




 
我考虑一下
 
&mdash;

**Comment by ResidualLaugh** [comment]
复制完整链接的功能是有的，在path标题右边复制URL，点一下试试，应该可以满足你的需求吧？
