### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by xElkomy** [momosecurity/FindSomething#39]
I want to express my sincere gratitude to all of you for creating this incredible extension. I truly appreciate it because I forked it and made the effort to adapt it to the Arabic language. I hope you don't mind the modification. Thank you once again for your contribution.

**Comment by ResidualLaugh** [comment]
Open source is all about sharing, so I'm glad you're translating it into Arabic for more people to use. The current version of the plugin does not yet support multilingualism, which is what I want to do in the future.
