### ISSUE TITLE
敏感信息识别增强

### ISSUE THREAD

**Issue by cloud-jie** [momosecurity/FindSomething#45]
版本：2.0.17
更换过浏览器，edge，Chrome问题依旧
对了，如果能在发现aksk时，同步出哪家的，就更好了
这个站是灯塔arl发现的，WebInfoHunter功能规则 ：https://github.com/TophantTechnology/ARL/blob/master/app/dicts/wih_rules.yml
![image](https://github.com/momosecurity/FindSomething/assets/63632785/74433b00-99c5-425a-a270-35c8ebc9c065)

站点：aHR0cHM6Ly95am0ueXVueHlhLmNvbQ==

**Comment by ResidualLaugh** [comment]
这个是因为页面上使用了iframe，当前版本没用检查iframe加载出来的内容，下个版本会增加检查逻辑。另外，感谢提醒WebInfoHunter，下个版本也考虑加一些规则上去。

**Comment by ResidualLaugh** [comment]
#47 这个版本加上了，感谢反馈
