### ISSUE TITLE
chrome 版本 129.0.6668.59（正式版本） (arm64) 在启动这个插件之后内存会占用过多导致浏览器崩溃

### ISSUE THREAD

**Issue by Ai577** [momosecurity/FindSomething#50]
通过单独开启插件发现这个问题，在chrome自带的任务管理器中观察不到扩展程序的内存占用。开启插件后，浏览器主进程内存占用会直线飙升直到浏览器崩溃

**Comment by newnewyingyingde** [comment]
在今天也发现了这个问题 Chrome版本139.0.7258.155，CPU i7-13650
